#!/bin/bash


print_mem(){
		memfree=$(($(grep -m1 'MemAvailable:' /proc/meminfo | awk '{print $2}') / 1024))
			echo -e " RAM $memfree |"
		}

print_temp(){
test -f /sys/class/thermal/thermal_zone0/temp || return 0
	echo " | Temp $(head -c 2 /sys/class/thermal/thermal_zone0/temp)C |" 
}

while
	xsetroot -name "$(uptime | awk '{print $3}) $(print_temp) $(print_mem) $(date) $(whoami)"

do

sleep 1

done
